[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bitstream-io = "3.1.0"
futures-channel = "0.3.31"
futures-util = { version = "0.3.31", features = ["futures-channel"] }
tokio = { version = "1.44.2", features = ["bytes", "full"] }
tokio-tungstenite = "0.26.2"
